import os


USE_RL = True
RL_TRAINING_MODE = False
RL_EVAL_MODE = True
LOAD_MODEL_ON_START = True
SAVE_MODEL_ON_EXIT = False

ALPHA = 0.1
GAMMA = 0.95
EPSILON_START = 0.0
EPSILON_MIN = 0.05
EPSILON_DECAY = 0.995

YELLOW_DURATION = 3
DEFAULT_GREEN_DURATION = 10
MIN_GREEN_DURATION = 5
MAX_GREEN_DURATION = 15
GREEN_DURATION_OPTIONS = (5, 10, 15)

CONGESTION_THRESHOLD = 20
CONGESTION_PENALTY_WEIGHT = 0.5
SWITCH_PENALTY = 1.0
QUEUE_CLEAR_BONUS = 1.0
ILLEGAL_STATE_PENALTY = 50.0
STARVATION_WAIT_THRESHOLD = 120
STARVATION_MIN_QUEUE = 1

STATE_BUCKET_SIZE = 5
WAIT_BUCKET_SIZE = 10
MAX_QUEUE_BUCKET = 6
MAX_WAIT_BUCKET = 6

MODEL_DIR = "models"
MODEL_PATH = os.path.join(MODEL_DIR, "traffic_qtable.pkl")
